In [1]:
1+1

2

In [2]:
4*2

8

In [3]:
1/2

0.5

In [4]:
1.0+2

3.0

In [5]:
4**2

16

In [7]:
16%2

0

In [8]:
10%3

1

#VARIABLE ASSIGNMENT

In [9]:
X=2
Y=4

In [10]:
Z=X*Y

In [11]:
Z

8

STRINGS

*SINGLE QUOTES*

In [12]:
'Hello world'

'Hello world'

In [13]:
x = 'Hello people'

In [14]:
print(x)

Hello people


*DOUBLE QUOTES*

In [15]:
"Hello world"

'Hello world'

In [16]:
"Quote and quote"

'Quote and quote'

In [17]:
y = "The python crash course is due!!"

In [18]:
print(y)

The python crash course is due!!


In [19]:
num = 12
name = 'Cynthia'

In [20]:
print('My name is {} and my number is: {}'.format(name, num))

My name is Cynthia and my number is: 12


LISTS

In [29]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [30]:
my_list = ['a', 'b', 'c', 'd']

In [31]:
my_list

['a', 'b', 'c', 'd']

In [32]:
my_list.append('e')

In [34]:
my_list

['a', 'b', 'c', 'd', 'e']

In [38]:
my_list.append('f')
my_list

['a', 'b', 'c', 'd', 'e', 'f', 'f']

In [39]:
my_list[6] = 'NUM'

In [40]:
my_list

['a', 'b', 'c', 'd', 'e', 'f', 'NUM']

In [33]:
list = [1,2,[3,4]]

In [35]:
list[2][1]

4

In [37]:
nested = [1,2,3,4,[6,7,9,12,['target']]]

In [38]:
print(nested[4][4][0])

target


In [39]:
nest =nested

In [40]:
nest

[1, 2, 3, 4, [6, 7, 9, 12, ['target']]]

In [41]:
print(nest[4][4][0])

target


Dictionaries

In [42]:
d = {'key1':[1,2,3], 'key2':[76,89]}

In [43]:
d

{'key1': [1, 2, 3], 'key2': [76, 89]}

In [48]:
d['key1']

[1, 2, 3]

In [49]:
d['key1'][2]

3

In [50]:
d['key2'][1]

89

In [51]:
d = {'k1':{'innerkey':[1,2,3]}}

In [52]:
d['k1']['innerkey'][1]

2

BOOLEAN

In [53]:
True

True

In [54]:
False

False

TUPLE


In [25]:
t = (1,2,3)

In [26]:
t

(1, 2, 3)

In [27]:
t[2]

3

NOTE:Diffrence between a tuple and a list is that a list is mutable but a tuple is not

SETS

In [58]:
{1,1,1,2,4,7,9,11,14}

{1, 2, 4, 7, 9, 11, 14}

In [59]:
s = ([1,2,3,4,7,9])

In [60]:
set(s)

{1, 2, 3, 4, 7, 9}

In [63]:
set={1,3,6,8}

In [64]:
set

{1, 3, 6, 8}

In [65]:
set.add(5)

In [66]:
set

{1, 3, 5, 6, 8}

COMPARISON OPERATORS

In [67]:
1>2

False

In [68]:
3<6

True

In [69]:
1>=0

True

In [70]:
4<=2

False

In [71]:
2==5

False

In [72]:
'HI'=='BYE'

False

LOGIC OPERATORS

In [74]:
(1>0) and (2<4)

True

In [75]:
(2 > 1) and (4>7)

False

In [76]:
(1>=3) or (4<6)

True

In [77]:
(1==2)or(2==3)

False

In [78]:
(1==1)or(2==2)

True

In [79]:
(3>2) or (2==1) or (1>9)

True

IF,ELIF AND ELSE STATEMENTS

In [80]:
if 1==2:
    print('first')
elif 2==4:
    print('middle')
else:
    print('last')

last


In [81]:
if 'hi'=='bye':
    print('yeaah')
else:
    print('Nah')

Nah


FOR LOOPS

In [82]:
sequence = [1,2,3,4,5,6]

In [83]:
for num in sequence:
    print(num)

1
2
3
4
5
6


WHILE LOOP

In [84]:
i = 1
while i<5:
    print('i is {}'.format(i))
    i = i+1

i is 1
i is 2
i is 3
i is 4


RANGE

In [85]:
for num in range(0, 5):
    print(num)

0
1
2
3
4


In [86]:
for num in range(15):
    print(num)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


LIST COMPREHENSION

In [88]:
x = [1,2,3,4,5]

In [90]:
out = []
for num in x:
    out.append(num**2)

In [91]:
print(out)

[1, 4, 9, 16, 25]


In [94]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

In [95]:
out = [num**2 for num in x]

In [96]:
print(out)

[1, 4, 9, 16, 25]


Defining function

In [104]:
def my_func(name = 'Ruth'):
    print('Hello'  + ' '+ name)

In [105]:
my_func()

Hello Ruth


In [106]:
def squares(num):
    return num**2

In [109]:
output = squares(4)

In [110]:
output

16

lamda


In [122]:
r = lambda num:num*3

In [112]:
seq = [1,2,3,4,5,6]

In [116]:
t = map(lambda num:num*3,seq)

In [119]:
t

In [120]:
print(t)

more methods

In [123]:
#splitting text

In [124]:
x = 'My name is Rand'

In [125]:
x.split()

['My', 'name', 'is', 'Rand']

In [126]:
y = 'Rands email is  rand@raandy.com'

In [128]:
y.split('@')

['Rands email is  rand', 'raandy.com']

In [136]:
#getting datafrom dictionaries

In [132]:
h = {'key1': 'fine', 'key2':'Thank you'}

In [133]:
h.keys()

dict_keys(['key1', 'key2'])

In [134]:
h.items()

dict_items([('key1', 'fine'), ('key2', 'Thank you')])

In [135]:
h.values()

dict_values(['fine', 'Thank you'])

In [137]:
#getting data from list

In [44]:
k= [2,3,4,7]

In [45]:
item = k.pop()

In [46]:
item

7

In [47]:
k

[2, 3, 4]

# NUMPY ARRAYS

#CREATING A NUMPY ARRAY 

In [ ]:
conda install numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
print(my_list)

[1, 2, 3, 4]


In [5]:
np.array(my_list)

array([1, 2, 3, 4])

In [6]:
my_list

[1, 2, 3, 4]

In [7]:
my_matrix = [[1,2,3], [4,5,6], [8,9,7]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [8, 9, 7]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [10]:
list = [7,8,9]

In [11]:
np.array(list)

array([7, 8, 9])

In [12]:
matrix = [[2,3,4], [5,6,7], [8,9,1]]

In [17]:
np.array(matrix)

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

# ARANGE

In [15]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.arange(0,1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [18]:
np.arange(10,40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

# ZEROS AND ONES

In [19]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# EYE

Identity matrix

In [25]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# LINSPACE

Return evenly spaced numbers given a specified range

In [28]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [52]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [32]:
np.linspace(0, 1000, 5)

array([   0.,  250.,  500.,  750., 1000.])

# RANDOM ARRAYS

Numpy has lot of ways to create random numbers

# RAND 

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [33]:
np.random.rand(2)

array([0.70557275, 0.30070175])

In [36]:
np.random.rand(5,5)

array([[0.64369302, 0.12103014, 0.71333722, 0.59527484, 0.42636485],
       [0.42273636, 0.70666251, 0.92367997, 0.50553868, 0.83573998],
       [0.69715902, 0.8159337 , 0.87345594, 0.2819591 , 0.18400599],
       [0.74480454, 0.61767924, 0.08979049, 0.89089094, 0.54077478],
       [0.72230343, 0.75690057, 0.07516293, 0.95505642, 0.23127457]])

In [37]:
np.random.rand(9)

array([0.02933473, 0.75621478, 0.94938722, 0.40327082, 0.02738239,
       0.83149717, 0.1066065 , 0.08320754, 0.79296863])

# RANDN

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [38]:
np.random.randn(9)

array([ 2.53114065, -3.39253054,  0.646379  ,  0.53884852, -1.10633228,
        0.55145876, -1.12963178,  0.89170577,  0.55560521])

In [39]:
np.random.randn(9,9)

array([[-1.87660432, -1.25228045, -0.22812648, -1.56838209, -1.3181535 ,
        -1.60467297, -0.39423013,  0.40322654,  0.27556111],
       [-1.15940902,  0.29638638, -0.41634222,  0.3039144 , -0.1232855 ,
        -0.46252997,  1.13092326, -0.16463054,  0.62840754],
       [-0.57850206, -0.70894242,  0.67426674, -0.00367844, -0.18179198,
         0.45245512,  0.32696536, -0.98173561,  3.24161601],
       [ 0.22812433, -1.17685948,  0.15490814, -0.0464227 ,  0.67530173,
         2.17791385, -0.33538442,  0.88987576,  0.0419358 ],
       [-0.42861666, -1.20322448, -1.11191948,  0.15255839,  0.32296141,
        -1.8321146 , -1.06061763, -0.15536764, -0.29944729],
       [-1.03221801, -1.03960228, -0.47781064, -2.04692252, -0.84869051,
         1.87754863, -0.649454  , -0.07198963,  0.23872019],
       [-0.79384553,  0.23549008,  1.58634615, -1.53069407,  0.64264899,
         1.43721759,  0.02010984,  1.21965273,  1.00460348],
       [ 0.28463331,  0.2016375 , -1.28841197, -0.63922888, -0

# RANDINT

Returns random numbers with low(inclusive) to high(exclusive)

In [41]:
np.random.randint(0, 10)

9

In [43]:
np.random.randint(0, 1000, 10)

array([ 40, 767, 425, 100, 544, 620, 480, 413, 525, 436])

ARRAY ATTRIBUTES AND METHODS

In [7]:
arr = np.arange(36)
ranarr = np.random.randint(0,50,10)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [9]:
ranarr

array([ 5,  2,  5, 18, 20,  2, 11, 23, 37, 14])

In [10]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

MAX, MIN, ARGMAX, ARGMIN

In [11]:
#maximum value
ranarr.max()

37

In [12]:
#position of the maximum number
ranarr.argmax()

8

In [13]:
#minimum value
ranarr.min()

2

In [14]:
#position of the minimum value
ranarr.argmin()

1

# SHAPE

IS AN ATTRIBUTE THAT ARRAY HAVE NOT A METHOD

In [53]:
arr.shape

(36,)

In [54]:
ranarr.shape

(10,)

In [56]:
arr.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [59]:
arr.reshape(36,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35]])

# DATA TYPE

In [60]:
ranarr.dtype

dtype('int32')

In [61]:
arr.dtype

dtype('int32')

# Numpy indexing and selection

In [ ]:
conda install numpy

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket indexing and selection

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#get value at index 8
arr[8]

8

In [6]:
#get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# BROADCASTING

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [53]:
#setting a value with index range
arr[:5]= 100

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
#reset array arr
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr_copy = arr.copy()

In [58]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
#important notes on slice
slice_of_arr = arr_copy[0:6]

In [60]:
slice_of_arr[:]=100

In [61]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [62]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# INDEXING FOR 2-D ARRAY

In [15]:
arr_2d = np.array([[5,9,7],[20,25,40],[35,40,45]])

In [16]:
arr_2d

array([[ 5,  9,  7],
       [20, 25, 40],
       [35, 40, 45]])

Indexing per row

In [17]:
arr_2d

array([[ 5,  9,  7],
       [20, 25, 40],
       [35, 40, 45]])

In [18]:
arr_2d[0][0]

5

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [99]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
conda install numpy

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
#selecting first row
arr_2d[0]

array([ 5, 10, 15])

In [5]:
#select 20
arr_2d[1][0]

20

In [6]:
#or 
arr_2d[1,0]

20

In [8]:
#slice 10,15,25 and 30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [9]:
#select the last row
arr_2d[2:,0:]

array([[35, 40, 45]])

# fancy indexing

In [19]:
#set up matrix
arr2d = np.zeros((10,10))

In [20]:
arr_length = arr2d.shape[1]

In [21]:
arr_length

10

In [22]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [15]:
arr2d[[2,4,6,9]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

# Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
bool_arr = arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [21]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
bol = arr<6
arr[bol]

array([0, 1, 2, 3, 4, 5])

# pandas

In [23]:
conda install pandas

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [24]:
import numpy as np

In [25]:
import pandas as pd

In [3]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [4]:
labels

['a', 'b', 'c']

In [5]:
my_data

[10, 20, 30]

In [6]:
arr

array([10, 20, 30])

In [7]:
d

{'a': 10, 'b': 20, 'c': 30}

In [11]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [17]:
tat =pd.Series(arr, labels)
tat

a    10
b    20
c    30
dtype: int32

In [18]:
tat['b']

20

In [19]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'KENYA', 'INDIA', 'JAPAN'])
ser1

USA      1
KENYA    2
INDIA    3
JAPAN    4
dtype: int64

In [20]:
ser2 = pd.Series([1,2,5,4], index =['USA', 'KENYA', 'UGANDA', 'JAPAN'])
ser2

USA       1
KENYA     2
UGANDA    5
JAPAN     4
dtype: int64

In [22]:
ser2['UGANDA']

5

In [24]:
ser1 + ser2

INDIA     NaN
JAPAN     8.0
KENYA     4.0
UGANDA    NaN
USA       2.0
dtype: float64

# pandas- dataframe

In [26]:
from numpy.random import randn

In [27]:
np.random.seed(101)

In [28]:
df = pd.DataFrame(randn(5,4), ['a','b','c','d','e'],['f','g','h','i'])

In [29]:
df

f         g         h         i
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

#selecting a column or columns

In [30]:
df['f']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: f, dtype: float64

In [31]:
df.i

a    0.503826
b    0.605965
c   -0.589001
d    0.955057
e    0.683509
Name: i, dtype: float64

In [32]:
df[['g','h']]

g         h
a  0.628133  0.907969
b -0.319318 -0.848077
c  0.740122  0.528813
d -0.758872 -0.933237
e  1.978757  2.605967

In [33]:
df['z'] = df['g']+df['h']

In [34]:
df

f         g         h         i         z
a  2.706850  0.628133  0.907969  0.503826  1.536102
b  0.651118 -0.319318 -0.848077  0.605965 -1.167395
c -2.018168  0.740122  0.528813 -0.589001  1.268936
d  0.188695 -0.758872 -0.933237  0.955057 -1.692109
e  0.190794  1.978757  2.605967  0.683509  4.584725

In [37]:
df.drop('z', axis = 1)

f         g         h         i
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

SELECTING ROWS USING .LOC AND .ILOC

In [38]:
df.loc['a']

f    2.706850
g    0.628133
h    0.907969
i    0.503826
z    1.536102
Name: a, dtype: float64

In [40]:
df.iloc[4]

f    0.190794
g    1.978757
h    2.605967
i    0.683509
z    4.584725
Name: e, dtype: float64

SELECTING SUBSET OF ROWS AND COLUMNS

In [42]:
df.loc['b','f']

0.6511179479432686

In [43]:
df.iloc[4,2]

2.60596727979128

In [44]:
df.loc[['c','d'],['g','h']]

g         h
c  0.740122  0.528813
d -0.758872 -0.933237

In [47]:
df.iloc[2:4,1:3]

g         h
c  0.740122  0.528813
d -0.758872 -0.933237

CONDITIONAL SELECTION

In [48]:
np.random.seed(101)

In [49]:
df = pd.DataFrame(randn(5,4), ['a','b','c','d','e'],['w','x','y','z'])

In [50]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [51]:
df>0

w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [52]:
df[df>0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [53]:
df[df['w']>0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [54]:
df[df['z']<0]

w         x         y         z
c -2.018168  0.740122  0.528813 -0.589001

In [55]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [57]:
df[df['x']>0][['y','z']]

y         z
a  0.907969  0.503826
c  0.528813 -0.589001
e  2.605967  0.683509

In [58]:
np.random.seed(50)

In [59]:
new = pd.DataFrame(randn(6,6),['a','b','c','d','e','f'],['j','k','l','m','n','o'])

In [60]:
new

j         k         l         m         n         o
a -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732
b -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194
c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770
d  0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715
e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307
f  1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465

In [73]:
new[new['j']<0][['m','n','o']]

m         n         o
a -1.464580  1.411946 -0.476732
b -1.327479  0.126338  0.862194

In [75]:
new[(new['l']<0) & (new['m']>1)]

j         k         l         m         n         o
c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770
e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307

In [76]:
new[(new['l']>0) | (new['j']>1)]

j         k         l         m         n         o
f  1.09521  1.338409 -1.368982  0.486428  0.753522  0.363465

INDEXING

In [77]:
new.reset_index()

index         j         k         l         m         n         o
0     a -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732
1     b -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194
2     c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770
3     d  0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715
4     e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307
5     f  1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465

In [78]:
new

j         k         l         m         n         o
a -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732
b -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194
c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770
d  0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715
e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307
f  1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465

In [86]:
newid = 'ca bd ht yt gg kl'.split()
newid

['ca', 'bd', 'ht', 'yt', 'gg', 'kl']

In [87]:
new['state'] = newid
new

j         k         l         m         n         o state
a -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732    ca
b -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194    bd
c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770    ht
d  0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715    yt
e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307    gg
f  1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465    kl

In [93]:
#you have to set the in place argument to truee so that it can replace the present index i.e new.reset_index(inplace = True)
new.reset_index()


index         j         k         l         m         n         o state
0     a -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732    ca
1     b -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194    bd
2     c  0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770    ht
3     d  0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715    yt
4     e  0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307    gg
5     f  1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465    kl

In [94]:
#new.set_index(state, inplace = True)
new.set_index('state')

j         k         l         m         n         o
state                                                            
ca    -1.560352 -0.030978 -0.620928 -1.464580  1.411946 -0.476732
bd    -0.780469  1.070268 -1.282293 -1.327479  0.126338  0.862194
ht     0.696737 -0.334565 -0.997526  1.598908  3.314075  0.987770
yt     0.123866  0.742785 -0.393956  0.148116 -0.412234 -0.160715
gg     0.139531  0.285469 -0.281262  1.710907 -0.149767  0.690307
kl     1.095210  1.338409 -1.368982  0.486428  0.753522  0.363465

MULTI-INDEX AND INDEX HIERACHY

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [96]:
#INDEX LEVEL
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [97]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -0.314710  1.373281
   2 -0.624417  0.375754
   3 -0.200416  0.743038
G2 1  0.857362 -1.506189
   2 -1.666352 -0.218995
   3 -0.358858  0.378528

In [99]:
df.loc['G1'].loc[1]['B']

1.373281168966614

In [103]:
df.loc['G2'].loc[2]['B']

-0.2189948025149798

In [104]:
df.index.names = ['Groups', 'Num']

In [105]:
df

A         B
Groups Num                    
G1     1   -0.314710  1.373281
       2   -0.624417  0.375754
       3   -0.200416  0.743038
G2     1    0.857362 -1.506189
       2   -1.666352 -0.218995
       3   -0.358858  0.378528

In [106]:
df.xs(3, level = 'Num')

A         B
Groups                    
G1     -0.200416  0.743038
G2     -0.358858  0.378528

DEALING WITH NULL VALUES

In [112]:
data = pd.DataFrame({'A':[1,2,np.nan], 'B':[4,7,5],'C':[8,np.nan,np.nan]})

In [113]:
data

A  B    C
0  1.0  4  8.0
1  2.0  7  NaN
2  NaN  5  NaN

In [116]:
data.fillna(0)

A  B    C
0  1.0  4  8.0
1  2.0  7  0.0
2  0.0  5  0.0

In [117]:
data.dropna()

A  B    C
0  1.0  4  8.0

In [118]:
data.dropna(axis=1)

B
0  4
1  7
2  5

In [119]:
data['A'].fillna(value = data['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

GROUPBY

In [120]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [128]:
DF = pd.DataFrame(data)

In [129]:
DF

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [131]:
DF.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [132]:
DF.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [133]:
DF.groupby('Company').std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [134]:
DF.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [136]:
DF.groupby('Company').describe().loc['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

In [137]:
DF.groupby('Company').describe().iloc[2]

Sales  count      2.000000
       mean     232.000000
       std      152.735065
       min      124.000000
       25%      178.000000
       50%      232.000000
       75%      286.000000
       max      340.000000
Name: MSFT, dtype: float64

MERGE, JOINS AND CONCATENATE

In [138]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [139]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [140]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])


In [142]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [143]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']}) 

In [145]:
pd.merge(left,right,how = 'inner', on = 'key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [146]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [147]:
pd.merge(left,right, on = ['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [148]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [149]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [152]:
dt= pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
dt.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [154]:
dt['col2'].unique()

array([444, 555, 666], dtype=int64)

In [155]:
dt['col2'].nunique()

3

In [156]:
dt[(dt['col1']>2) & (dt['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [157]:
def times2(x):
    return x*2
    

In [158]:
dt['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [160]:
dt.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [161]:
dt.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

pivot table

In [164]:
DATA = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

X = pd.DataFrame(DATA)

In [165]:
X

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [169]:
X.pivot_table(values = 'D', index = ['A','B'], columns = ['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN